name       : python-pyzmq
version    : 17.1.2
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/p/pyzmq/pyzmq-17.1.2.tar.gz : a72b82ac1910f2cf61a49139f4974f994984475f771b0faa730839607eeedddf
license    : BSD-3-Clause
component  : programming.python
summary    : Python bindings for zeromq
description: |
    This package contains Python bindings for ØMQ. ØMQ is a lightweight and fast messaging implementation
builddeps  :
    - pkgconfig(libzmq)
    - cython
rundeps    :
    - python-tornado
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
