name       : python-pyzmq
version    : 16.0.2
release    : 1
source     :
    - https://github.com/zeromq/pyzmq/archive/v16.0.2.tar.gz : 717dd902c3cf432b1c68e7b299ad028b0de0d0a823858e440b81d5f1baa2b1c1
license    : BSD-3-Clause
component  : programming.python
summary    : Python bindings for zeromq
description: |
    This package contains Python bindings for ØMQ. ØMQ is a lightweight and fast messaging implementation
builddeps  :
    - pkgconfig(libzmq)
    - pkgconfig(python-3.5)
    - cython
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
