name       : python-pyzmq
version    : 16.0.4
release    : 3
source     :
    - https://github.com/zeromq/pyzmq/archive/v16.0.4.tar.gz : 6381457420b0108226dab730b6728a4c2158e0286f614b2e89ef905f1c8fb580
license    : BSD-3-Clause
component  : programming.python
summary    : Python bindings for zeromq
description: |
    This package contains Python bindings for ØMQ. ØMQ is a lightweight and fast messaging implementation
builddeps  :
    - pkgconfig(libzmq)
    - cython
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
