name       : python-pyzmq
version    : 17.0.0
release    : 6
source     :
    - https://github.com/zeromq/pyzmq/archive/v17.0.0.tar.gz : e6c6394bfe32e81b4ccb917fe24c3d7637c894f3c5f4698ccac513bda1f675d9
license    : BSD-3-Clause
component  : programming.python
summary    : Python bindings for zeromq
description: |
    This package contains Python bindings for ØMQ. ØMQ is a lightweight and fast messaging implementation
builddeps  :
    - pkgconfig(libzmq)
    - cython
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
