name       : python-pyzmq
version    : 18.1.1
release    : 10
source     :
    - https://github.com/zeromq/pyzmq/archive/v18.1.1.tar.gz : b79afea8701970f0da15218abf9c2c6a39ab3dd8daaef25b868f55f9d9304687
license    : BSD-3-Clause
component  : programming.python
summary    : Python bindings for zeromq
description: |
    This package contains Python bindings for ØMQ. ØMQ is a lightweight and fast messaging implementation
builddeps  :
    - pkgconfig(libzmq)
    - cython
rundeps    :
    - python-tornado
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
