name       : python-pyzmq
version    : 24.0.1
release    : 19
source     :
    - https://github.com/zeromq/pyzmq/archive/refs/tags/v24.0.1.tar.gz : ce8ea133817947828852847e7b940df41e7672183411ca7175102c05d5dbffad
homepage   : https://github.com/zeromq/pyzmq
license    :
    - BSD-3-Clause
    - LGPL-3.0-or-later
component  : programming.python
summary    : Python bindings for zeromq
description: |
    This package contains Python bindings for ØMQ. ØMQ is a lightweight and fast messaging implementation
builddeps  :
    - pkgconfig(libzmq)
    - cython
    - python-packaging
rundeps    :
    - python-tornado
build      : |
    %python3_setup
install    : |
    %python3_install
