name       : python-pyzmq
version    : 16.0.3
release    : 2
source     :
    - https://github.com/zeromq/pyzmq/archive/v16.0.3.tar.gz : 680b03afd8acab0c61cab825e4c358cbb25ce05eb922e3044e4408694010dcea
license    : BSD-3-Clause
component  : programming.python
summary    : Python bindings for zeromq
description: |
    This package contains Python bindings for ØMQ. ØMQ is a lightweight and fast messaging implementation
builddeps  :
    - pkgconfig(libzmq)
    - cython
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
