name       : python-pyzmq
version    : 19.0.2
release    : 11
source     :
    - https://github.com/zeromq/pyzmq/archive/v19.0.2.tar.gz : ed67b5ffe8a87c88c5a19bf6f2d64ca7e3c325a2f6cc30f989f5f57d2205bada
homepage   : https://github.com/zeromq/pyzmq
license    : 
    - BSD-3-Clause
    - LGPL-3.0-or-later
component  : programming.python
summary    : Python bindings for zeromq
description: |
    This package contains Python bindings for ØMQ. ØMQ is a lightweight and fast messaging implementation
builddeps  :
    - pkgconfig(libzmq)
    - cython
rundeps    :
    - python-tornado
build      : |
    %python3_setup
install    : |
    %python3_install
