name       : python-pyzmq
version    : 22.1.0
release    : 12
source     :
    - https://github.com/zeromq/pyzmq/archive/refs/tags/v22.1.0.tar.gz : 5598c8aee7c5dd8d7994255bf6b2a5c2011578d2db33456b8c963f4145592b28
homepage   : https://github.com/zeromq/pyzmq
license    :
    - BSD-3-Clause
    - LGPL-3.0-or-later
component  : programming.python
summary    : Python bindings for zeromq
description: |
    This package contains Python bindings for ØMQ. ØMQ is a lightweight and fast messaging implementation
builddeps  :
    - pkgconfig(libzmq)
    - cython
rundeps    :
    - python-tornado
build      : |
    %python3_setup
install    : |
    %python3_install
