name       : python-pyzmq
version    : 18.0.1
release    : 8
source     :
    - https://files.pythonhosted.org/packages/f8/48/5416696b9f2eacc7d1f9fe3a7187ad54d769e09585ec0b59c137ab5c7575/pyzmq-18.0.1.tar.gz : 8b319805f6f7c907b101c864c3ca6cefc9db8ce0791356f180b1b644c7347e4c
license    : BSD-3-Clause
component  : programming.python
summary    : Python bindings for zeromq
description: |
    This package contains Python bindings for ØMQ. ØMQ is a lightweight and fast messaging implementation
builddeps  :
    - pkgconfig(libzmq)
    - cython
rundeps    :
    - python-tornado
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
