name       : python-pyzmq
version    : 22.3.0
release    : 16
source     :
    - https://github.com/zeromq/pyzmq/archive/refs/tags/v22.3.0.tar.gz : 66b6e4fc47181bd560a55a0a15df15e1fc237b92665787d894a51aa70b02e049
homepage   : https://github.com/zeromq/pyzmq
license    :
    - BSD-3-Clause
    - LGPL-3.0-or-later
component  : programming.python
summary    : Python bindings for zeromq
description: |
    This package contains Python bindings for ØMQ. ØMQ is a lightweight and fast messaging implementation
builddeps  :
    - pkgconfig(libzmq)
    - cython
rundeps    :
    - python-tornado
build      : |
    %python3_setup
install    : |
    %python3_install
