name       : python-pyzmq
version    : 23.2.1
release    : 18
source     :
    - https://github.com/zeromq/pyzmq/archive/refs/tags/v23.2.1.tar.gz : c0137cd4545d4b95ced21eba178d98f8a451de317cf25a7a7302ec23242578a8
homepage   : https://github.com/zeromq/pyzmq
license    :
    - BSD-3-Clause
    - LGPL-3.0-or-later
component  : programming.python
summary    : Python bindings for zeromq
description: |
    This package contains Python bindings for ØMQ. ØMQ is a lightweight and fast messaging implementation
builddeps  :
    - pkgconfig(libzmq)
    - cython
    - python-packaging
rundeps    :
    - python-tornado
build      : |
    %python3_setup
install    : |
    %python3_install
